rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.5
  - 2.3.1
before_install:
  - gem update bundler
before_script:
  - bundle install --gemfile=examples/rails4_root/Gemfile
  - bundle install --gemfile=examples/sinatra_root/Gemfile
branches:
  only:
    - master
cache: bundler
sudo: false
